#include "lexer/token.h"

namespace kinglet {

const char *token_type_name(TokenType type) {
  switch (type) {
  case TokenType::AUTO:
    return "AUTO";
  case TokenType::INT:
    return "INT";
  case TokenType::FLOAT:
    return "FLOAT";
  case TokenType::DOUBLE:
    return "DOUBLE";
  case TokenType::BOOL:
    return "BOOL";
  case TokenType::STRING:
    return "STRING";
  case TokenType::VOID:
    return "VOID";
  case TokenType::BYTE:
    return "BYTE";
  case TokenType::CONST:
    return "CONST";
  case TokenType::RETURN:
    return "RETURN";
  case TokenType::IF:
    return "IF";
  case TokenType::ELSE:
    return "ELSE";
  case TokenType::FOR:
    return "FOR";
  case TokenType::WHILE:
    return "WHILE";
  case TokenType::BREAK:
    return "BREAK";
  case TokenType::CONTINUE:
    return "CONTINUE";
  case TokenType::GUARD:
    return "GUARD";
  case TokenType::INSPECT:
    return "INSPECT";
  case TokenType::WHEN:
    return "WHEN";
  case TokenType::IMPORT:
    return "IMPORT";
  case TokenType::EXPORT:
    return "EXPORT";
  case TokenType::NAMESPACE:
    return "NAMESPACE";
  case TokenType::USING:
    return "USING";
  case TokenType::STRUCT:
    return "STRUCT";
  case TokenType::ENUM:
    return "ENUM";
  case TokenType::TRAIT:
    return "TRAIT";
  case TokenType::SPAWN:
    return "SPAWN";
  case TokenType::SELECT:
    return "SELECT";
  case TokenType::TRUE:
    return "TRUE";
  case TokenType::FALSE:
    return "FALSE";
  case TokenType::NULL_:
    return "NULL";
  case TokenType::PLUS:
    return "PLUS";
  case TokenType::MINUS:
    return "MINUS";
  case TokenType::STAR:
    return "STAR";
  case TokenType::SLASH:
    return "SLASH";
  case TokenType::PERCENT:
    return "PERCENT";
  case TokenType::EQUAL:
    return "EQUAL";
  case TokenType::EQUAL_EQUAL:
    return "EQUAL_EQUAL";
  case TokenType::BANG_EQUAL:
    return "BANG_EQUAL";
  case TokenType::LESS:
    return "LESS";
  case TokenType::GREATER:
    return "GREATER";
  case TokenType::LESS_EQUAL:
    return "LESS_EQUAL";
  case TokenType::GREATER_EQUAL:
    return "GREATER_EQUAL";
  case TokenType::AMP_AMP:
    return "AMP_AMP";
  case TokenType::PIPE_PIPE:
    return "PIPE_PIPE";
  case TokenType::BANG:
    return "BANG";
  case TokenType::AMP:
    return "AMP";
  case TokenType::PIPE:
    return "PIPE";
  case TokenType::CARET:
    return "CARET";
  case TokenType::TILDE:
    return "TILDE";
  case TokenType::LESS_LESS:
    return "LESS_LESS";
  case TokenType::GREATER_GREATER:
    return "GREATER_GREATER";
  case TokenType::PIPE_GREATER:
    return "PIPE_GREATER";
  case TokenType::ARROW:
    return "ARROW";
  case TokenType::FAT_ARROW:
    return "FAT_ARROW";
  case TokenType::QUESTION:
    return "QUESTION";
  case TokenType::COLON_COLON:
    return "COLON_COLON";
  case TokenType::DOT:
    return "DOT";
  case TokenType::DOT_DOT:
    return "DOT_DOT";
  case TokenType::DOT_DOT_DOT:
    return "DOT_DOT_DOT";
  case TokenType::PLUS_EQUAL:
    return "PLUS_EQUAL";
  case TokenType::MINUS_EQUAL:
    return "MINUS_EQUAL";
  case TokenType::STAR_EQUAL:
    return "STAR_EQUAL";
  case TokenType::SLASH_EQUAL:
    return "SLASH_EQUAL";
  case TokenType::LEFT_PAREN:
    return "LEFT_PAREN";
  case TokenType::RIGHT_PAREN:
    return "RIGHT_PAREN";
  case TokenType::LEFT_BRACE:
    return "LEFT_BRACE";
  case TokenType::RIGHT_BRACE:
    return "RIGHT_BRACE";
  case TokenType::LEFT_BRACKET:
    return "LEFT_BRACKET";
  case TokenType::RIGHT_BRACKET:
    return "RIGHT_BRACKET";
  case TokenType::COMMA:
    return "COMMA";
  case TokenType::SEMICOLON:
    return "SEMICOLON";
  case TokenType::COLON:
    return "COLON";
  case TokenType::INTEGER:
    return "INTEGER";
  case TokenType::FLOAT_LIT:
    return "FLOAT_LIT";
  case TokenType::STRING_LIT:
    return "STRING_LIT";
  case TokenType::CHAR_LIT:
    return "CHAR_LIT";
  case TokenType::IDENTIFIER:
    return "IDENTIFIER";
  case TokenType::END_OF_FILE:
    return "END_OF_FILE";
  case TokenType::ERROR:
    return "ERROR";
  }

  return "UNKNOWN";
}

} // namespace kinglet
